[project]
name = "music-ocean-bot"
version = "0.1.0"
description = "meow"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram~=3.21.0",
    "aiohttp~=3.12.15",
    "asyncpg>=0.31.0",
    "brotli>=1.2.0",
    "dishka~=1.7.2",
    "playwright>=1.55.0",
    "pycryptodome~=3.23.0",
    "pydantic>=2.11.10",
    "pydantic-settings>=2.12.0",
    "rich~=14.2.0",
    "sqlalchemy~=2.0.44",
]
